*&---------------------------------------------------------------------*
*& Report ZHIEN_ITAB_PART04
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZHIEN_ITAB_PART04.


*-- 3. Basic Inserting Data --
*-- 4. SINGLE ACCESS: Basic Read Data --
*-- 5. LOOP ACCESS: Basic Loop --
*-- 6. SINGLE ACCESS WITH >, <, <= , >=, <>, IN, LIKE: Basic Read Data --
*-- 7. Modifying Data using Work Area --
*-- B. Modifying Data using Field Symbol --
*-- 9. Delete a record from Internal Table --
*-- 10. Clear an Internal Table -

*----SORT TABLE
TYPES: BEGIN OF TY_SPFLI,
         CARRID    TYPE SPFLI-CARRID, "Airline
         CONNID    TYPE SPFLI-CONNID, "Flight Number
         CITYFROM  TYPE SPFLI-CITYFROM, "Departure City
         CITYTO    TYPE SPFLI-CITYTO, " Arrival city
         COUNTRYFR TYPE SPFLI-COUNTRYFR, "Departure Country
         COUNTRYTO TYPE SPFLI-COUNTRYTO, "Arrival Country
         NOTE      TYPE TEXT40,
       END OF TY_SPFLI.

*-- 1. Basic Table Creation -
DATA:GT_S_FLISCH TYPE SORTED TABLE OF TY_SPFLI
                WITH NON-UNIQUE KEY CARRID CONNID.

DATA:GT_SU_FLISCH TYPE SORTED TABLE OF TY_SPFLI
                WITH UNIQUE KEY CARRID CONNID.
*-- 2. Basic Appending Data --


*GS_FLISCH-CARRID = 'VA'.
*GS_FLISCH-CONNID = '2268'.
*GS_FLISCH-CITYFROM = 'HA NOI'.
*GS_FLISCH-CITYTO ='DA NANG'.
*GS_FLISCH-COUNTRYFR = 'VN'.
*GS_FLISCH-COUNTRYTO = 'VN'.
*APPEND GS_FLISCH TO GT_S_FLISCH.
*
*GS_FLISCH-CARRID = 'ZA'.
*GS_FLISCH-CONNID = '0556'.
*GS_FLISCH-CITYFROM = 'HA NOI'.
*GS_FLISCH-CITYTO ='DA NANG'.
*GS_FLISCH-COUNTRYFR = 'VN'.
*GS_FLISCH-COUNTRYTO = 'VN'.
*APPEND GS_FLISCH TO GT_S_FLISCH.

*
*LOOP AT GT_S_FLISH INTO GS_GLISCCH.
*  WRITE:/ GS_FLISCH-CARRID ,
*          GS_FLISCH-CONNID  ,
*          GS_FLISCH-CITYFROM ,
*          GS_FLISCH-CITYTO ,
*          GS_FLISCH-COUNTRYFR,
*          GS_FLISCH-COUNTRYTO.
*ENDLOOP.

*-- 3. Basic Inserting Data --
*DATA: GS_FLISCH TYPE TY_SPFLI.
*
*GS_FLISCH-CARRID = 'VA'.
*GS_FLISCH-CONNID = '2268'.
*GS_FLISCH-CITYFROM = 'HA NOI'.
*GS_FLISCH-CITYTO ='DA NANG'.
*GS_FLISCH-COUNTRYFR = 'VN'.
*GS_FLISCH-COUNTRYTO = 'VN'.
*INSERT GS_FLISCH INTO TABLE GT_SU_FLISCH.
**FINT POSITION FOR INSERTING
**INSERTING
*
*GS_FLISCH-CARRID = 'AA'.
*GS_FLISCH-CONNID = '0556'.
*GS_FLISCH-CITYFROM = 'HA NOI'.
*GS_FLISCH-CITYTO ='DA NANG'.
*GS_FLISCH-COUNTRYFR = 'VN'.
*GS_FLISCH-COUNTRYTO = 'VN'.
*INSERT GS_FLISCH INTO TABLE GT_SU_FLISCH.
*
*GS_FLISCH-CARRID = 'AA'.
*GS_FLISCH-CONNID = '0556'.
*GS_FLISCH-CITYFROM = 'HA NOI'.
*GS_FLISCH-CITYTO ='DA NANG'.
*GS_FLISCH-COUNTRYFR = 'VN'.
*GS_FLISCH-COUNTRYTO = 'VN'.
*INSERT GS_FLISCH INTO TABLE GT_SU_FLISCH.
*
*LOOP AT GT_SU_FLISCH INTO GS_FLISCH.
*  WRITE:/ GS_FLISCH-CARRID ,
*          GS_FLISCH-CONNID  ,
*          GS_FLISCH-CITYFROM ,
*          GS_FLISCH-CITYTO ,
*          GS_FLISCH-COUNTRYFR,
*          GS_FLISCH-COUNTRYTO.
*ENDLOOP.

*WRITE:/ GS_FLISCH.

*-- 4. SINGLE ACCESS: Basic Read Data --
DATA: GS_FLISCH TYPE TY_SPFLI.

SELECT * FROM SPFLI INTO CORRESPONDING FIELDS OF TABLE GT_S_FLISCH
  UP TO 20 ROWS.

*LOOP AT GT_SU_FLISCH INTO GS_FLISCH.
*  WRITE:/ GS_FLISCH-CARRID ,
*          GS_FLISCH-CONNID  ,
*          GS_FLISCH-CITYFROM ,
*          GS_FLISCH-CITYTO ,
*          GS_FLISCH-COUNTRYFR,
*          GS_FLISCH-COUNTRYTO.
*ENDLOOP.
*
*CLEAR  GS_FLISCH.
*READ TABLE GT_SU_FLISCH INTO GS_FLISCH " Linear Search
* WITH KEY CARRID = 'DL'.
*
*
*IF SY-SUBRC = 0.
*  WRITE:/ 'READ: ',
*      GS_FLISCH-CARRID ,
*      GS_FLISCH-CONNID  ,
*      GS_FLISCH-CITYFROM ,
*      GS_FLISCH-CITYTO ,
*      GS_FLISCH-COUNTRYFR,
*      GS_FLISCH-COUNTRYTO.
*ENDIF.
*
*READ TABLE GT_SU_FLISCH INTO GS_FLISCH " Binary Search WITH KEY
* WITH TABLE KEY CARRID = 'DL'
*                CONNID = '1699'.
*
*IF SY-SUBRC = 0.
*  WRITE:/ 'READ KEY: ',
*      GS_FLISCH-CARRID ,
*      GS_FLISCH-CONNID  ,
*      GS_FLISCH-CITYFROM ,
*      GS_FLISCH-CITYTO ,
*      GS_FLISCH-COUNTRYFR,
*      GS_FLISCH-COUNTRYTO.
*ENDIF.
*
*CLEAR  GS_FLISCH.
*READ TABLE GT_SU_FLISCH INTO GS_FLISCH " Binary Search NO ENOUGHT KEY,
* WITH KEY CARRID = 'DL'                " USER FOR TABLE SORTED AND KEY SEACH IS PRIMARY KEY
*            BINARY SEARCH."
*
*IF SY-SUBRC = 0.
*  WRITE:/ 'Binary Search: ',
*      GS_FLISCH-CARRID ,
*      GS_FLISCH-CONNID  ,
*      GS_FLISCH-CITYFROM ,
*      GS_FLISCH-CITYTO ,
*      GS_FLISCH-COUNTRYFR,
*      GS_FLISCH-COUNTRYTO.
*ENDIF.



*Calculatins time
*DATA: T1 TYPE P LENGTH 8 DECIMALS 3,
*      T2 TYPE P LENGTH 8 DECIMALS 3,
*      T3 TYPE P LENGTH 8 DECIMALS 3.
*GET RUN TIME FIELD T1.
*READ TABLE GT_S_FLISCH INTO GS_FLISCH " normAl linear SeArch
*WITH KEY CARRID = 'DL'
*          CONNID ='1699'.
*GET RUN TIME FIELD T2.
*T3 = T2 - T1.
*IF SY-SUBRC = 0.
*  WRITE: / SY-TABIX, T3, 'ms'.
*ENDIF.
*
*GET RUN TIME FIELD T1.
*READ TABLE GT_S_FLISCH INTO GS_FLISCH" BINARY SEARCH
*WITH KEY CARRID = 'DL'
*          CONNID = ' 1699'
*BINARY SEARCH.
*GET RUN TIME FIELD T2.
*T3 = T2 - T1.
*IF SY-SUBRC = 0.
*  WRITE: / SY-TABIX, T3, 'MS'.
*ENDIF.
*
*GET RUN TIME FIELD T1.
*READ TABLE GT_S_FLISCH INTO GS_FLISCH " BInary seach by default
*WITH TABLE KEY CARRID = 'DL'
*                CONNID = '1699'.
*
*GET RUN TIME FIELD T2.
*T3 = T2 - T1.
*IF SY-SUBRC = 0.
*  WRITE: / SY-TABIX, T3, 'MS'.
*ENDIF.

*-- 5. LOOP ACCESS: Basic Loop --
*NO DIFF
*LOOP AT GT_S_FLISCH INTO GS_FLISCH
*WHERE CITYFROM = 'NEW YORK'.
*  WRITE: / 'LOOP:',
*  GS_FLISCH-CARRID,
*  GS_FLISCH-CONNID,
*  GS_FLISCH-CITYFROM,
*  GS_FLISCH-CITYTO,
*  GS_FLISCH-COUNTRYFR,
*  GS_FLISCH-COUNTRYTO.
*  ENDLOOP.

  LOOP AT GT_S_FLISCH INTO GS_FLISCH.
    IF GS_FLISCH-COUNTRYFR <> GS_FLISCH-COUNTRYTO.
      GS_FLISCH-NOTE = 'International'.
    ELSE.
      GS_FLISCH-NOTE = 'Domestic'.
      GS_FLISCH-CARRID = '**'.
    ENDIF.
    MODIFY GT_S_FLISCH FROM GS_FLISCH.
  ENDLOOP.
  LOOP AT GT_s_fLISCH INTO GS_FLISCH.
    WRITE: / 'LOOP Modified: ',
    GS_FLISCH-CARRID,
    GS_FLISCH-CONNID,
    GS_FLISCH-CITYFROM,
    GS_FLISCH-CITYTO,
    GS_FLISCH-COUNTRYFR,
    GS_FLISCH-COUNTRYTO,
    GS_FLISCH-NOTE.
  ENDLOOP.
