*&---------------------------------------------------------------------*
*& Report ZHIEN_ITAB_PART03
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZHIEN_ITAB_PART03.

*& 3 TYPES TABLE


*&-Standard Table

TYPES: BEGIN OF TY_SPFLI,
         CARRID    TYPE SPFLI-CARRID, "Airline
         CONNID    TYPE SPFLI-CONNID, "Flight Number
         CITYFROM  TYPE SPFLI-CITYFROM, "Departure City
         CITYTO    TYPE SPFLI-CITYTO, " Arrival city
         COUNTRYFR TYPE SPFLI-COUNTRYFR, "Departure Country
         COUNTRYTO TYPE SPFLI-COUNTRYTO, "Arrival Country
         NOTE      TYPE TEXT40,
       END OF TY_SPFLI.
*1. Basic Table Creation --
*DATA:GT_FLISCH TYPE TABLE OF TY_SPFLI.
*
*DATA:GT_FLISCH TYPE STANDARD TABLE of  TY_SPFLI
*                WITH NON-UNIQUE DEFAULT KEY " Define Primary key.
*                INITIAL SIZE 0.

DATA : GT_FLISCH TYPE STANDARD TABLE OF TY_SPFLI
                          WITH NON-UNIQUE KEY CARRID CONNID.

*2. Basic Appending Data --

DATA: GS_FLISCH TYPE TY_SPFLI.

GS_FLISCH-CARRID = 'VA'.
GS_FLISCH-CONNID = '2268'.
GS_FLISCH-CITYFROM = 'HA NOI'.
GS_FLISCH-CITYTO ='DA NANG'.
GS_FLISCH-COUNTRYFR = 'VN'.
GS_FLISCH-COUNTRYTO = 'VN'.
APPEND GS_FLISCH TO GT_FLISCH.

GS_FLISCH-CARRID = 'VA'.
GS_FLISCH-CONNID = '0275'.
GS_FLISCH-CITYFROM = 'HO CHI MINH'.
GS_FLISCH-CITYTO = 'SAN FRANSISCO'.
GS_FLISCH-COUNTRYFR = 'VN'.
GS_FLISCH-COUNTRYTO = 'US'.
APPEND GS_FLISCH TO GT_FLISCH.

GS_FLISCH-CARRID = 'AL'.
GS_FLISCH-CONNID = '0636'.
GS_FLISCH-CITYFROM = 'HO CHI MINH'.
GS_FLISCH-CITYTO = 'DA NANG'.
GS_FLISCH-COUNTRYFR = 'VN'.
GS_FLISCH-COUNTRYTO = 'VN'.
APPEND GS_FLISCH TO GT_FLISCH.

GS_FLISCH-CARRID = 'CA'.
GS_FLISCH-CONNID = '7822'.
GS_FLISCH-CITYFROM = 'BEIJING'.
GS_FLISCH-CITYTO ='DA NANG'.
GS_FLISCH-COUNTRYFR = 'CN'.
GS_FLISCH-COUNTRYTO = 'VN'.
APPEND GS_FLISCH  TO GT_FLISCH.

GS_FLISCH-CARRID = 'UA'.
GS_FLISCH-CONNID = '0275'.
GS_FLISCH-CITYFROM = 'HO CHI MINH'.
GS_FLISCH-CITYTO = 'SAN FRANSISCO'.
GS_FLISCH-COUNTRYFR = 'VN'.
GS_FLISCH-COUNTRYTO = 'US'.
APPEND GS_FLISCH TO GT_FLISCH.


*3. Basic Inserting Data --
GS_FLISCH-CARRID = 'UA'.
GS_FLISCH-CONNID = '3014'.
GS_FLISCH-CITYFROM = 'HO CHI MINH'.
GS_FLISCH-CITYTO ='HA NOI'.
GS_FLISCH-COUNTRYFR = 'VN'.
GS_FLISCH-COUNTRYTO = 'VN'.
DATA(V_POS) = 2.
INSERT GS_FLISCH INTO GT_FLISCH INDEX V_POS.

*
*LOOP AT GT_FLISCH INTO GS_FLISCH.
*  WRITE: / 'ALL', GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO.
*ENDLOOP.
*
**4. SINGLE ACCESS: Basic Read Data --
*READ TABLE GT_FLISCH INTO GS_FLISCH
*    WITH KEY CITYFROM = 'HO CHI MINH'.
*IF SY-SUBRC = 0.
*  WRITE: / 'READ:', GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO.
*ENDIF.
*
**5. LOOP ACCESS: Basic Loop --
*LOOP AT GT_FLISCH INTO GS_FLISCH
*  WHERE CITYFROM = 'HO CHI MINH'.
*  WRITE: / 'LOOP:', SY-TABIX, GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO.
*ENDLOOP.
*
**-- 6. SINGLE ACCESS WITH >, < <= >=, <>, IN, LIKE: Basic Read Data --
*LOOP AT GT_FLISCH INTO GS_FLISCH
*  WHERE CONNID > 1000.
*  EXIT.
*ENDLOOP.
*
*IF SY-SUBRC = 0.
*  WRITE: / 'LOOP EXIT: ', SY-TABIX, GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO.
*ENDIF.

*7. Modifying Data using Work Area --
*LOOP AT GT_FLISCH INTO GS_FLISCH.
*  IF GS_FLISCH-COUNTRYFR <> GS_FLISCH-COUNTRYTO .
*    GS_FLISCH-NOTE = 'Intenation'.
*  ELSE.
*    GS_FLISCH-NOTE = 'Domestic'.
*  ENDIF.
*  MODIFY GT_FLISCH FROM GS_FLISCH.
*ENDLOOP.
*
*LOOP AT GT_FLISCH INTO GS_FLISCH.
*  WRITE: / 'MODIFIED', GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO, GS_FLISCH-NOTE.
*ENDLOOP.


* 8. Modifying Data using Field Symbol --
FIELD-SYMBOLS: <GFS_FLISCH> TYPE TY_SPFLI.
LOOP AT GT_FLISCH ASSIGNING <GFS_FLISCH>.
  IF <GFS_FLISCH>-COUNTRYFR <> <GFS_FLISCH>-COUNTRYTO .
    <GFS_FLISCH>-NOTE = 'Intenation'.
  ELSE.
    <GFS_FLISCH>-NOTE = 'Domestic'.
  ENDIF.

ENDLOOP.

LOOP AT GT_FLISCH INTO GS_FLISCH.
  WRITE: / 'MODIFIED BY FIELD SYMBOLS', SY-TABIX, GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO, GS_FLISCH-NOTE.
ENDLOOP.

*9. Delete a record from Internal Table --
DELETE GT_FLISCH
  WHERE CARRID = 'UA' AND
        CONNID = '3014'.

*LOOP AT GT_FLISCH INTO GS_FLISCH.
*  WRITE: / 'AFTER DELETE', SY-TABIX, GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO, GS_FLISCH-NOTE.
*ENDLOOP.

DELETE GT_FLISCH INDEX 1.
LOOP AT GT_FLISCH INTO GS_FLISCH.
  WRITE: / 'AFTER DELETE', SY-TABIX, GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO, GS_FLISCH-NOTE.
ENDLOOP.

*10. Clear an Internal Table -- I
CLEAR: GT_FLISCH.
* USER ITAB WITH HEADER LINE, CLEAR DATA AND MEMORY OF TABLE. USE AT THE END OF PROGRAM.
FREE: GT_FLISCH.

LOOP AT GT_FLISCH INTO GS_FLISCH.
  WRITE: / 'AFTER CLEAR', SY-TABIX, GS_FLISCH-CARRID, GS_FLISCH-CONNID, GS_FLISCH-CITYFROM, GS_FLISCH-CITYTO, GS_FLISCH-NOTE.
ENDLOOP.
WRITE:/ 'AFTER CLEAR SY-SUBRC: ', SY-SUBRC.
